<?php
/**
 * Created by PhpStorm.
 * User: versus
 * Date: 20/01/18
 * Time: 13:27
 */

namespace PrestationBundle\Tests\Controller;


use PHPUnit\Framework\TestCase;
use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;

class ActionControllerTest extends WebTestCase
{
    protected $client;
    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->client = static::createClient();
    }

    /**
     * - create a new action
     * @test
     */
    public function new_action()
    {
        $action = new Action('car wash', 15);
        $crawler = $this->client->request('GET', '/prestations');

        $this->assertEquals(200, 'GET', '/prestations');
        $this->assertContains('Prestations', $client->getResponse()->getContent());
        $this->assertEquals('car wash', $action->getName());
        $this->assertEquals(15, $action->getPrice());
    }
}