imports:
    - { resource: config_dev.yml }

services:
    _defaults:
        public: true
    test.ProductBundle\Manager\WorkshopManager: '@ProductBundle\Manager\WorkshopManager'
    test.CoreBundle\Specifics\Resources: '@CoreBundle\Specifics\Resources'

doctrine:
    dbal:
        url: 'sqlite:///%kernel.project_dir%/var/data/test.sqlite'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_sqlite
        path: '%kernel.project_dir%/var/data/data.sqlite'

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true
