# ******************************** ACTIVITY *********************************
prestation_activity:
    resource: "@PrestationBundle/Resources/config/routing/activity.yml"
    prefix:   /prestations/activity

