services:
#    prestation.example:
#        class: PrestationBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    prestation.manager_activity:
        class: PrestationBundle\Manager\ActivityManager
        arguments: ["@service_container"]