<?php

namespace UserBundle\Repository;

/**
 * DeveloperRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeveloperRepository extends \Doctrine\ORM\EntityRepository
{
}
