# .......................................................................... #
# - WEB ***
# .......................................................................... #

# ******************************** WORKSHOP *********************************
product_homepage:
    path:     /
    defaults: { _controller: ProductBundle:Default:index }

product_workshop:
    resource: "@ProductBundle/Resources/config/web/workshop.yml"
    prefix:   /workshops

product_vehicule_auto:
    resource: "@ProductBundle/Resources/config/web/vehicule.yml"
    prefix:   /vehicules-auto

# .......................................................................... #
# - API ***
# .......................................................................... #

# ******************************** WORKSHOP *********************************
api_product_workshop:
    resource: "@ProductBundle/Resources/config/api/workshop.yml"
    prefix:   /api/workshops
