product_homepage:
    path:     /
    defaults: { _controller: ProductBundle:Default:index }

# ******************************** WORKSHOP *********************************
product_workshop:
    resource: "@ProductBundle/Resources/config/routing/workshop.yml"
    prefix:   /workshops

