<?php

namespace CoreBundle\Repository;

/**
 * DateLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DateLogRepository extends \Doctrine\ORM\EntityRepository
{
}
