services:
#    order.example:
#        class: OrderBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    setNewReference:
        class: OrderBundle\Service\ReferenceBuilder
        arguments: [  '@security.context' , '@doctrine.orm.entity_manager' ]
