services:
#    order.example:
#        class: OrderBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    order.reference_builder:
        class: OrderBundle\Service\ReferenceBuilder
        arguments: [  '@service_container' , '@doctrine.orm.entity_manager' ]
